Сделать вёрстку и стили
GoveRaven/kanban-board pull request #1
Opened 2023-11-30 17:47 UTC by GoveRaven

Сверстать:
- [ ] шаблон для шапки
- [ ] шаблон для задач
- [ ] первую страницу
- [ ] вторую страницу
Добавить стили для:
- [ ] шапки
- [ ] задач
- [ ] первой страницы
- [ ] второй страницы

2023-11-30 19:18 UTC, Lexeria requested changes

2023-11-30 19:18 UTC, Lexeria commented on template/CSS/header.css
> +body {
Кажется, что не хватает сбросов стилей или хотя бы переопределение базовых с помощью комбинации `*`, `*::before` и `*::after`. Как минимум, важно, чтобы на странице был `box-sizing: border-box;`

2023-11-30 19:18 UTC, Lexeria commented on template/CSS/header.css
> +    background-color: #2F72E5;
Могу ошибаться, но кажется этот цвет еще где-то используется в проекте. Лучше вытащить в переменные. И в целом большинство цветов обычно вытаскиваются, так как на сайте плюс-минус небольшой набор цветов из одной палитры, которые повторяются и комбинируются между собой, меняясь в опасити или тип того

2023-11-30 19:18 UTC, Lexeria commented on template/CSS/header.css
> +    padding: 0 100px;
Ахах, за что ты так бедный паддинг отделил от других свойств?

2023-11-30 19:18 UTC, Lexeria commented on template/CSS/header.css
> +    padding: 0 100px;
Можно и так, но вообще по макету есть паддинги сверху и снизу — `36px`. А надпись и инфа о юзере забирают место по контенту

2023-11-30 19:18 UTC, Lexeria commented on template/CSS/header.css
> +    font-size: 36px;
Тоже можно вытащить как переменную, если похожий размер будет использоваться где-то еще

2023-11-30 19:18 UTC, Lexeria commented on template/CSS/header.css
> +    transform: rotateX(180deg);
Вот такого быть не должно. Если приходится переворачивать, то значит иконка могла быть неправильной изначально. Лучше уточнить у дизайнера и мб попросить корректный вариант

2023-11-30 19:18 UTC, Lexeria commented on template/CSS/header.css
> +.user_logOutBtn-open {
Я бы постарался следить за логическим порядком, как он выстраивается в хтмл страничке. От родителей к вложенным элементам. Сначала стоит описать `user__logOut`, а потом уже `user_logOutBtn-open`. У тебя, кстати, тут одна земля вместо двух

2023-11-30 19:18 UTC, Lexeria commented on template/CSS/header.css
> +    color: #B74E5F;
Тоже стоит вынести в переменную, если цвет еще где-то используется

2023-11-30 19:18 UTC, Lexeria commented on template/CSS/header.css
> +    border-radius: 6px;
Скругление бывает часто оч похожим у разных элементов. Если это так, то тоже можно вытащить в переменную

2023-11-30 19:18 UTC, Lexeria commented on template/CSS/header.css
> +}
Потерял конец строчки

2023-11-30 19:18 UTC, Lexeria commented on template/img/Аватарка.png
По-хорошему все должно быть в svg, эта аватарка по идее тоже могла быть им. Но не критично, просто другие форматы могут шакалиться при масштабировании или по-разному отображаться на экранах с разной плотностью пикселей

2023-11-30 19:18 UTC, Lexeria commented on template/template.html
> +<!DOCTYPE html>
У нас темплейт вместо кастомного элемента?

2023-11-30 19:18 UTC, Lexeria commented on template/template.html
> +          <img src="img/Аватарка.png" alt="Аватар" class="user_avatar" />
Я бы старался по-возможности избегать в путях до файла названий на русском

2023-11-30 19:18 UTC, Lexeria commented on template/template.html
> +          <img src="img/Аватарка.png" alt="Аватар" class="user_avatar" />
У тебя тут одна земля вместо двух

2023-11-30 19:18 UTC, Lexeria commented on template/template.html
> +          <span class="user_name">user name</span>
Тут тоже одна земля

2023-11-30 19:18 UTC, Lexeria commented on template/template.html
> +          <span class="user_logOutBtn">▼</span>
И тут

2023-11-30 19:18 UTC, Lexeria commented on template/template.html
> +            <img src="img/Exit.svg" alt="" />
Лучше не оставлять изображения без альтернативного описания — слабозрячим людям скринридеры проговаривают эти alt'ы

2023-11-30 19:18 UTC, Lexeria commented on template/template.html
> +            <span class="logOut_title"> Выйти</span>
Одна земля опять и пробел перед «Выйти»

2023-11-30 19:25 UTC, GoveRaven commented on template/template.html
> +          <img src="img/Аватарка.png" alt="Аватар" class="user_avatar" />
одна земля?

2023-11-30 20:29 UTC, GoveRaven commented on template/CSS/header.css
> +body {
я не буду это писать в стиле для темплейта, но в стилях для страниц уже допишу. Ибо страница с темплейтами чисто для меня, чтобы я писал и брал от туда шаблоны

2023-11-30 20:43 UTC, GoveRaven commented on template/CSS/header.css
> +    padding: 0 100px;
Во-первых, случайно получилось его так выделить. Там наверное было ещё какое-то свойство, которое я потом стёр.
Во-вторых, по макету у шапки фиксированная высотка 100. Содержимое шапки расположено по середине, поэтому я использовал флексбокс, чтобы сделать по середине. Как по мне, то так больше похоже на макет, а если сделать фиксированный паддинг сверху и снизу (который в макете 28, а не 36), то будет как-то много пространства

2023-11-30 20:44 UTC, GoveRaven commented on template/CSS/header.css
> +    padding: 0 100px;
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/d85a7104-2767-488d-83b1-de51a0a28b67)
Вот пруф, что паддинг 28

2023-11-30 20:46 UTC, GoveRaven commented on template/CSS/header.css
> +    padding: 0 100px;
Вот шапка с вертикальным паддингом 0 и 28px
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/4d3f6ab8-27f5-4f92-9cd1-b7bcd7048be4)
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/48e8288e-21da-498d-bcbe-b7eee8c42c3f)

2023-11-30 20:47 UTC, GoveRaven commented on template/CSS/header.css
> +    font-size: 36px;
Я проверил и 36px встречается только в шапке

2023-11-30 20:48 UTC, GoveRaven commented on template/CSS/header.css
> +    transform: rotateX(180deg);
Обсуждали в телеге. Контент у него перевёрнутый
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/e1000390-9057-4099-9b3b-63c7079fa05e)

2023-11-30 20:49 UTC, GoveRaven commented on template/template.html
> +            <img src="img/Exit.svg" alt="" />
дописал "Иконка выхода"

2023-12-01 08:44 UTC, Lexeria commented on template/CSS/header.css
> +body {
Понял, но как минимум тот же box-sizing или сброс каких-то отступов/чего-то еще оч важно и чтобы правильно написать стили в изолированном месте

2023-12-01 08:47 UTC, Lexeria commented on template/CSS/header.css
> +    padding: 0 100px;
<img width="1098" alt="image" src="https://github.com/GoveRaven/kanban-board/assets/39084375/3e835d86-01df-45ef-986f-eb7fe06b51e9">

Видимо, фигма шалит. Я обычно отступы смотрю в месте выше на скрине или в правом углу:
<img width="270" alt="image" src="https://github.com/GoveRaven/kanban-board/assets/39084375/20cfcb45-171c-4d94-8ed3-0f51fa9de532">

Давай оставим, как у тебя, такие отклонения от макеты нормальные, тем более, что тут и вправду шапка с фиксированной высотой, а контент по центру

2023-12-01 08:48 UTC, Lexeria commented on template/CSS/header.css
> +    font-size: 36px;
Тогда можно оставить, но это с закосом на будущее, мб где-то еще будет использоваться такой текст. Но в нашем проекте легко прослеживается, что нет

2023-12-01 08:49 UTC, Lexeria commented on template/template.html
> +          <img src="img/Аватарка.png" alt="Аватар" class="user_avatar" />
Символ нижнее подчеркивание, эт земля называется

2023-12-01 13:58 UTC, GoveRaven commented on template/CSS/header.css
> +.user_logOutBtn-open {
Но у в html идёт сначала `user_logOutBtn`, а потом `user__logOut`
Пруф:
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/3e44e5a4-727b-4c10-831f-848c4399079c)

2023-12-01 14:00 UTC, GoveRaven commented on template/CSS/header.css
> +    color: #B74E5F;
Вынес в `--logout`

2023-12-01 14:01 UTC, GoveRaven commented on template/CSS/header.css
> +}
я не понял какой конец строки поменял

2023-12-01 14:02 UTC, GoveRaven commented on template/img/Аватарка.png
я изначально делал svg, но там были какие-то проблемы с ней и она скачивалась сломанной

2023-12-01 14:02 UTC, GoveRaven commented on template/template.html
> +<!DOCTYPE html>
не понял вопроса

2023-12-01 19:22 UTC, Lexeria commented on template/CSS/header.css
> +.user_logOutBtn-open {
А, понял, я по неймингу не состыковался. По сути этот значок не совсем кнопка, на кнопку больше похож обычный logOut. Но да, тогда все окей

2023-12-01 19:24 UTC, Lexeria commented on template/CSS/header.css
> +}
<img width="209" alt="image" src="https://github.com/GoveRaven/kanban-board/assets/39084375/94768889-a8b1-4354-80c7-ba8eef4b66bf">
Вот эта красная штучка, обычно сама ставится, когда сохраняешь файл. Хотя мб для CSS и не нужно, но гитхаб чет ругается

2023-12-01 19:25 UTC, Lexeria commented on template/template.html
> +<!DOCTYPE html>
Не совсем понял, зачем ты темплейт делаешь. Или это не темплейт в свое привычном понимании, а что-то экспериментное для тебя, чтобы просто поиграться пока и потом удалишь?

2023-12-01 19:49 UTC, GoveRaven commented on template/CSS/header.css
> +    background-color: #2F72E5;
сделал переменную `--main-color`

2023-12-01 19:49 UTC, GoveRaven commented on template/CSS/header.css
> +}
в конце сделать пустую строку?

2023-12-01 19:49 UTC, GoveRaven commented on template/template.html
> +<!DOCTYPE html>
типо, я сделал страничку, чтобы тестировать темплейты. 
Изначально мы же хотели импортировать темплейты из html, поэтому и был создан изначально этот файл. Потом мы придумали делать через кастомные элементы. Но тогда надо же как-то проверять то, что происходит внутри кастомных элементов
Я всё ещё не понял вопроса. Вопрос к названию файла?

2023-12-01 19:50 UTC, Lexeria commented on template/template.html
> +<!DOCTYPE html>
Вопрос к необходимости этого файла. Но пока похоже, что я правильно понял, что он для экспериментов и потом ты удалишь за ненадобностью, ведь так?

2023-12-01 19:52 UTC, GoveRaven commented on template/template.html
> +<!DOCTYPE html>
но он нужен, чтобы ты оценил правильность написания кастомного элемента

2023-12-01 20:03 UTC, Lexeria commented on template/template.html
> +    <link rel="stylesheet" href="CSS/task.css" />
Я бы называл маленькими буквами лучше, ты же расширение тоже не большими пишешь. А еще лучше назвать папку не CSS, а styles, ибо это история в частности не только про CSS

2023-12-01 20:04 UTC, Lexeria commented on template/template.html
> +    </style>
Сомнительно, но окэй
Почему так?)

2023-12-01 20:30 UTC, GoveRaven commented on template/template.html
> +    </style>
Чтобы стили для body лежали не в header или tasks, в которых ты ожидаешь увидеть соответствующие стили

2023-12-01 20:41 UTC, Lexeria requested changes

2023-12-01 20:41 UTC, Lexeria commented on template/style/task.css
> +  box-sizing: border-box;
Не-не, лучше это прописывать через звездочки, как я писал. Но если это в Shadow DOM, тогда ок

2023-12-01 20:41 UTC, Lexeria commented on template/style/task.css
> +  /* убрать на странице */
Такие комменты лучше оставлять с префиксом `TODO:`, тогда тебе еще и `TODO Highlight` подсветит, а если есть `TODO Tree`, то все такие тудушки можно будет удобно найти по проекту. Ну, либо, по классике через `ctrl+shift+f` и ввести `TODO`

2023-12-01 20:41 UTC, Lexeria commented on template/style/task.css
> +  border-color: var(--backlog);
Обычно лучше писать суффикс `-color`, но не обязательно, просто если кому-то будет IDE/редактор подсказывать CSS переменные, не все сразу поймут по названию, что это переменная для цвета. Аналогично для классов для других типов задач ниже

2023-12-01 20:43 UTC, GoveRaven commented on template/style/task.css
> +  box-sizing: border-box;
точно, да

2023-12-02 13:51 UTC, Lexeria requested changes

2023-12-02 13:51 UTC, Lexeria commented on template/style/root.css
> +}
Конец строчки потерялся

2023-12-02 13:51 UTC, Lexeria commented on style/root.css
> +}
Потерял конец строчки

2023-12-02 13:51 UTC, Lexeria commented on templates.js
> +// Шаблон шапки
Такие комментарии лучше не писать, у тебя за это должны говорить твои названия переменных, классов, файлов

2023-12-02 13:51 UTC, Lexeria commented on templates.js
> +class templateOFHeader extends HTMLElement {
Название класса не с большой буквы разве?

2023-12-02 13:51 UTC, Lexeria commented on templates.js
> +class templateOFTasks extends HTMLElement {
Аналогично тут про название классов

2023-12-02 13:51 UTC, Lexeria commented on templates.js
> +class templateOFTasks extends HTMLElement {
Я бы по-хорошему разделил шаблоны по файлам, чтобы было понятно, в какой папке лежит код какого-то кастомного элемента

2023-12-02 13:51 UTC, Lexeria commented on style/root.css
> +  height: 100vh;
А если контент будет больше, чем высота вьюпорта, что будет? Он обрежется, мы покажем его со скроллом или как?

2023-12-02 13:51 UTC, Lexeria commented on style/root.css
>    font-family: Inter;
По-хорошему надо предоставлять альтернативы, если у пользователя не подгрузится шрифт, или его не будет в стандартном наборе или еще что-то. Хорошая практика писать свой шрифт, потом стандартный, а потом семейство шрифтов по типу `sans-serif` как-нибудь

2023-12-02 13:51 UTC, Lexeria commented on style/root.css
> +  height: 100%;
Аналогичный вопрос про обрезание контента

2023-12-02 13:51 UTC, Lexeria commented on style/root.css
> +  --empty-color: #A1A1A1;
`empty` — немного сумбурное название, пустой цвет?

2023-12-02 13:51 UTC, Lexeria commented on style/task.css
> +}
Нет конца строчки

2023-12-02 13:51 UTC, Lexeria commented on template/style/task.css
> +}
Конец строчки пропустил

2023-12-02 13:51 UTC, Lexeria commented on template/style/task.css
> +  background-color: inherit;
inherit? Почему?

2023-12-02 13:51 UTC, Lexeria commented on template/template.html
> +      <div class="task empty">Сделать домашку</div>
по-хорошему наименовать не просто `empty/trashCan/ready/inProgress`, а как есть состояния в БЭМе через одну землю — `task_empty` или `task_in-progress` например

2023-12-02 13:51 UTC, Lexeria commented on login.html
> +        <input type="text" class="new-task_title" />
Плейсхолдер потом добавишь?

2023-12-02 13:51 UTC, Lexeria commented on login.html
> +        <button class="new-task_btn"></button>
Текст у кнопки потом добавишь?

2023-12-02 13:51 UTC, Lexeria commented on login.html
> +          <button><img src="img/cross.svg" alt="крестик">Очистить</button>
Православный?)
Но справедливости ради скринридер зачитает это со словом «Очистить», поэтому должно быть понятно. Но лучшее более явно описывать

2023-12-02 13:52 UTC, Lexeria commented on package-lock.json
Вижу package-lock.json, а обычный package.json куда потерялся?

2023-12-02 14:32 UTC, GoveRaven commented on templates.js
> +class templateOFHeader extends HTMLElement {
теперь с большой

2023-12-02 14:32 UTC, GoveRaven commented on templates.js
> +class templateOFTasks extends HTMLElement {
теперь с большой и разделил

2023-12-02 14:39 UTC, GoveRaven commented on style/root.css
> +  height: 100vh;
но контент и так пролистывается, если будет много контента
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/781a7fa8-49a9-4147-bd10-fd5e959b1851)
Я понадобвлял задачи и появился скроллер.
Лучше заменить на min-height?

2023-12-02 14:39 UTC, GoveRaven commented on style/root.css
>    font-family: Inter;
какой возьмём для стандарта?

2023-12-02 14:40 UTC, GoveRaven commented on style/root.css
> +  height: 100%;
заменить на min-height?

2023-12-02 14:52 UTC, GoveRaven commented on template/style/task.css
> +  background-color: inherit;
я думал, что inherit сбрасывает свойство, но это делает initial. Перепутал слова

2023-12-02 14:58 UTC, GoveRaven commented on template/template.html
> +      <div class="task empty">Сделать домашку</div>
переименовал

2023-12-02 15:00 UTC, GoveRaven commented on login.html
> +        <button class="new-task_btn"></button>
а это я что-то забыл добавить

2023-12-02 15:01 UTC, GoveRaven commented on package-lock.json
а я не знаю. Его и не было

2023-12-02 15:01 UTC, GoveRaven commented on login.html
> +          <button><img src="img/cross.svg" alt="крестик">Очистить</button>
Переименовал в 'крест'

2023-12-02 17:35 UTC, Lexeria commented on style/root.css
> +  height: 100vh;
В идеале да, потому что ты фиксируешь контент, ограничивая вьюпортом, а он же может за вьюпорт выходить

2023-12-02 17:36 UTC, Lexeria commented on style/root.css
>    font-family: Inter;
Можно Arial или любой другой без засечек

2023-12-02 17:37 UTC, Lexeria commented on style/root.css
> +  height: 100%;
Ну, в этом случае 100% будет нормальным. Тут скорее вопрос для твоего понимания различий min-height и height, их комбинации и когда что лучше использовать. Можно погуглить

2023-12-02 17:38 UTC, Lexeria commented on package-lock.json
А откуда тогда package-lock взялся?

2023-12-02 17:42 UTC, Lexeria requested changes

2023-12-02 17:42 UTC, Lexeria commented on template-of-header.js
> +class TemplateOFHeader extends HTMLElement {
Лучше назвать просто HeaderTemplate. Меньше букв, смысл такой же, порядок слов привычный в нейминге

2023-12-02 17:42 UTC, Lexeria commented on template-of-task.js
> +
Пропустил конец строчки

2023-12-02 17:42 UTC, Lexeria commented on template-of-task.js
> +class TemplateOFTasks extends HTMLElement {
Аналогично про нейминг

2023-12-02 17:42 UTC, Lexeria commented on style/root.css
> +  --no-task-color: #A1A1A1;
Не критично, но лучше tasks. У нас же не одной конкретной задачи нет, а всех

2023-12-02 17:42 UTC, Lexeria commented on index.html
> +    <script src="template-of-header.js"></script>
Тут тоже нейминг

2023-12-02 17:42 UTC, Lexeria commented on login.html
> +    <script src="template-of-header.js"></script>
Тут и ниже нейминг тоже

2023-12-02 17:42 UTC, Lexeria commented on login.html
> +          <button><img src="img/cross.svg" alt="крест">Очистить</button>
Лучше не стало, православный крест/крестик)

2023-12-02 17:42 UTC, Lexeria commented on login.html
> +        <button class="new-task_btn"><img src="img/Plus.svg" alt="плюс">Добавить</button>
Изолированное описание, лучше добавить контекста, что это картинка/иконка/символ

2023-12-02 17:46 UTC, GoveRaven commented on style/root.css
> +  height: 100vh;
так, лучше написать min-height?

2023-12-02 17:47 UTC, GoveRaven commented on style/root.css
>    font-family: Inter;
дописал

2023-12-02 17:48 UTC, GoveRaven commented on package-lock.json
хз, но у меня правда нет package.json
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/c41415e2-970a-46f7-8798-507015236525)

2023-12-02 17:49 UTC, GoveRaven commented on template-of-header.js
> +class TemplateOFHeader extends HTMLElement {
переименовал

2023-12-02 17:49 UTC, GoveRaven commented on template-of-task.js
> +class TemplateOFTasks extends HTMLElement {
переименовал

2023-12-02 17:51 UTC, GoveRaven commented on login.html
> +          <button><img src="img/cross.svg" alt="крест">Очистить</button>
а как? Это же крест и никак по другому

2023-12-02 17:52 UTC, GoveRaven commented on login.html
> +          <button><img src="img/cross.svg" alt="крест">Очистить</button>
символ крестика?

2023-12-02 17:57 UTC, GoveRaven commented on login.html
> +        <input type="text" class="new-task_title" />
добавил

2023-12-02 18:00 UTC, GoveRaven commented on style/root.css
> +  height: 100%;
Я понимаю, что height - фиксированная высота, которую объект не увеличит. А min-height - минимальная высота, которой может быть объект, и в перспективе стать больше.
Ааааааа. Я ограничиваю его. Поэтому лучше написать min-height. Понял

2023-12-02 18:03 UTC, GoveRaven commented on style/root.css
> +  --no-task-color: #A1A1A1;
исправил

2023-12-02 18:04 UTC, GoveRaven commented on index.html
> +    <script src="template-of-header.js"></script>
переименовал просто в header и task

2023-12-02 18:04 UTC, GoveRaven commented on login.html
> +    <script src="template-of-header.js"></script>
переименовал просто в header и task

2023-12-02 18:11 UTC, Lexeria commented on login.html
> +          <button><img src="img/cross.svg" alt="крест">Очистить</button>
Как и с плюсом, это мини замечание, просто крест без контекста. Но тут спасает, что есть слово «Очистить» рядом

2023-12-02 18:13 UTC, Lexeria requested changes

2023-12-02 18:13 UTC, Lexeria commented on style/task.css
> +.tasks_no-task {
Не-не, тут task оставить. Ты же используешь это как карточку задачи, а не задач. А вот в конце s добавить

2023-12-02 18:13 UTC, Lexeria commented on template/style/task.css
> +.tasks_no-task {
И тут тоже самое

2023-12-02 18:19 UTC, GoveRaven commented on style/task.css
> +.tasks_no-task {
я случайно не туда поставил

2023-12-02 18:23 UTC, Lexeria commented on package-lock.json
А в чем тогда прикол лок-файла?

2023-12-02 18:24 UTC, GoveRaven commented on package-lock.json
а я не знаю. Удалить его?

2023-12-02 18:24 UTC, Lexeria commented on package-lock.json
Аналогично с папкой node_modules. Ты скачивал какие-то библиотеки?

2023-12-03 10:06 UTC, Lexeria requested changes

2023-12-03 10:06 UTC, Lexeria commented on index.html
> +    <link rel="stylesheet" href="style/index.css">
Если это общий для всей страницы, я бы его повыше добавил:
1) Сброс стилей
2) Стили для всех страниц
3) Оставшиеся стили для специфичных или отдельных элементов: шапка/футер/...

2023-12-03 10:06 UTC, Lexeria commented on index.html
> +      <button class="main__btn"><img src="img/github-icon.svg" alt="иконка Гитхаба"><span>Sign in with GitHub</span></button>
На другой странице может получится похожий класс, потому что это не понятно какая кнопка внутри аж всего main. Лучше обозвать соответствующим образом, btn не конкретное название

2023-12-03 10:06 UTC, Lexeria commented on style/header.css
> +  font-size: var(--font-size-big);
Лайк за ренейминг)

2023-12-03 10:06 UTC, Lexeria commented on style/index.css
> +    font-size: var(--font-size-bigest);
А тут почему-то остался `bigest`. Если есть `big` и нужно что-то еще больше, можно воспользоваться `large` или подобрать другое слово, иначе не понятно, что за `bigest` и что делать, если появится что-то больше него

2023-12-03 10:06 UTC, Lexeria commented on style/index.css
> +}
Конец строчки пропустил

2023-12-03 10:06 UTC, Lexeria commented on style/index.css
> +    font-size: var(--font-size-for-btn);
Если это размер для всех кнопок, то норм. Но если для определенной кнопки, лучше переименовать, а то не понятно

2023-12-03 10:06 UTC, Lexeria commented on style/index.css
> +    padding: 16px 72px 16px 24px;
Ух, вот это я намудрил с макетом, но пусть будет так)

2023-12-03 10:06 UTC, Lexeria commented on style/index.css
> +    margin: 24px;
А зачем нам отступ внешний со всех сторон? Если это отступ от заголовка «Авторизация», то лучше делать отступы по направлению потоков элементов, то есть вправую и нижнюю сторону, иначе получится каша и отступы где-то схлопнуться. Я бы на твоем месте написал бы просто `margin-bottom` от заголовка или `gap` в `main`, если больше элементов не планируется и на всех страничках одинаково по отступам

2023-12-03 10:06 UTC, Lexeria commented on style/root.css
> +  --font-size-bigest: 40px;
Про название это написал, но еще раз продублирую, что лучше переименовать явно. Если это для заголовков или чего-то еще, то можно использовать не `big`, `small`, а `header` например

2023-12-03 10:06 UTC, Lexeria commented on style/root.css
>    --no-tasks-color: #A1A1A1;
Я бы делал все в едином стиле: у тебя выше все в нижнем регистре, а тут нет

2023-12-03 10:06 UTC, Lexeria commented on style/root.css
> +  --font-size-for-btn: 28px;
Про это название тож написал, явное лучше неявного

2023-12-03 10:06 UTC, Lexeria commented on style/root.css
> +  flex-grow: 1;
Лайк за то, что додумался до этого

2023-12-03 10:16 UTC, GoveRaven commented on index.html
> +    <link rel="stylesheet" href="style/index.css">
это для конкретно первой страницы. Что-то общее для всех страниц я писал в root.css

2023-12-03 10:17 UTC, GoveRaven commented on style/index.css
> +    font-size: var(--font-size-bigest);
исправил

2023-12-03 10:17 UTC, GoveRaven commented on style/index.css
> +}
добавил

2023-12-03 10:18 UTC, GoveRaven commented on style/index.css
> +    padding: 16px 72px 16px 24px;
вот у меня тоже были к этому вопросы. Я добавлял это с неуверенностью

2023-12-03 10:20 UTC, GoveRaven commented on style/index.css
> +    margin: 24px;
я хотел написать margin-top. Но что-то подумал, что можно нули поставить в margin и в итоге не написал

2023-12-03 10:20 UTC, GoveRaven commented on style/root.css
> +  flex-grow: 1;
я посмотрел в интернете 👀

2023-12-03 10:23 UTC, GoveRaven commented on style/index.css
> +    font-size: var(--font-size-for-btn);
переименовал в `--font-size-signInBtn`

2023-12-03 10:23 UTC, GoveRaven commented on index.html
> +      <button class="main__btn"><img src="img/github-icon.svg" alt="иконка Гитхаба"><span>Sign in with GitHub</span></button>
переименовал в `main__signInBtn`

2023-12-03 10:25 UTC, GoveRaven commented on style/root.css
> +  --font-size-bigest: 40px;
переименовал в `--font-size-large`

2023-12-03 10:26 UTC, GoveRaven commented on style/root.css
>    --no-tasks-color: #A1A1A1;
переименовал в `--noTasks-color`

2023-12-03 10:26 UTC, GoveRaven commented on style/root.css
> +  --font-size-for-btn: 28px;
переименовал `--font-size-signInBtn`

2023-12-03 10:41 UTC, Lexeria commented on index.html
> +    <link rel="stylesheet" href="style/index.css">
Но все равно, общие стили для страницы должны быть идти раньше, чем стили для шапки. От общего к частному как говорится

2023-12-03 10:42 UTC, Lexeria commented on style/index.css
> +    padding: 16px 72px 16px 24px;
В такие моменты можно уточнить, что имел в виду автор. А автор делал все на коленке)
Тут не учитываются некоторые случаи, но в целом все нормасно, все в соответствии с дизайном

2023-12-03 10:42 UTC, Lexeria commented on style/index.css
> +    margin: 24px;
Вот лучше без `margin-top`, а делать по направлению потока

2023-12-03 10:43 UTC, Lexeria commented on style/root.css
>    --no-tasks-color: #A1A1A1;
Не-не-не, не `lowerCase` и `snake-case`, а нижний регистр. Я про цвета имел в виду, то есть значения переменных)
Но названия переменных тоже лучше в одном стиле, да

2023-12-03 10:44 UTC, Lexeria commented on style/root.css
>    --no-tasks-color: #A1A1A1;
Кст, почему `trashCan`, а не `canTrash`?

2023-12-03 10:44 UTC, Lexeria commented on style/root.css
> +  flex-grow: 1;
Ахах, а понятно же все, не просто копипаст из инета?

2023-12-03 10:55 UTC, GoveRaven commented on index.html
> +    <link rel="stylesheet" href="style/index.css">
я переместил эту строчку

2023-12-03 10:56 UTC, GoveRaven commented on style/index.css
> +    margin: 24px;
то бишь с gap?

2023-12-03 10:58 UTC, GoveRaven commented on style/root.css
>    --no-tasks-color: #A1A1A1;
Аааа. Понял. Я просто копировал цвета из фигмы, и не обратил внимание, что там большие буквы
Переводчик выдал `trash can`

2023-12-03 10:59 UTC, GoveRaven commented on style/root.css
> +  flex-grow: 1;
да. Я помню, что делает flex-grow, но словами объяснить сложно. Я забываю про существование самого такого свойства

2023-12-03 11:42 UTC, Lexeria commented on style/index.css
> +    margin: 24px;
Либо `gap`, либо `margin-bottom` у заголовка

2023-12-03 11:44 UTC, Lexeria commented on style/root.css
>    --no-tasks-color: #A1A1A1;
Если это существительное, а не глагол, то да. Если подразумевалось возможность, то стоит начинать с `can`

2023-12-03 12:02 UTC, GoveRaven commented on style/root.css
>    --no-tasks-color: #A1A1A1;
это существительное, значит да

2023-12-09 09:32 UTC, Lexeria requested changes

2023-12-09 09:32 UTC, Lexeria commented on template/style/root.css
> +  --newTaskBtn-border-focus: #2237F1;
Опять разный стиль: где-то верхним, где-то нижним регистром

2023-12-09 09:32 UTC, Lexeria commented on template/style/root.css
> +  --lightblue-color-hover: #4280ea;
В целом можно написать, какой цвет будет при наведении, но лучше написать, а для каких наведений он подразумевался, например `btn-background-hover-color`. И тогда станет понятно, что эту переменную мы будем использовать:
1. При наведении
2. Для кнопок
3. Для смены/задания цвета

2023-12-09 09:32 UTC, Lexeria commented on template/style/root.css
> +  --disabledBtn-color: #d8d8d8;
root-файл оч разросся из-за цветов для задачек. Кажется, логичнее для них сделать отдельный файл и изолировать стили там, а еще лучше, возможно, спрятать их в shadow и задавать цвета внутри него

2023-12-09 09:32 UTC, Lexeria commented on template/style/task.css
> +  fill: none;
Нам точно нужен `fill`? Если да, то зачем?

2023-12-09 09:32 UTC, Lexeria commented on template/style/task.css
> +}
А вот это лучше убрать, если будем через аттрибуты скрывать

2023-12-09 09:32 UTC, Lexeria commented on template/style/task.css
> +  flex-grow: 1;
Кажется, что `flex-grow` можно и отдельно задать, чтобы контент всегда был растянут вплоть до карандаша, если сейчас это не так. Но если с этим все хорошо, когда много текста, то можно и тут оставить

2023-12-09 09:32 UTC, Lexeria commented on template/style/task.css
> +  stroke: black;
Он же и так `black` изначально, если верить изначальному `task__icon` селектору

2023-12-09 09:32 UTC, Lexeria commented on template/style/task.css
> +  background-color: initial;
А это зачем?

2023-12-09 10:58 UTC, GoveRaven commented on template/style/root.css
> +  --newTaskBtn-border-focus: #2237F1;
исправил

2023-12-09 10:59 UTC, GoveRaven commented on template/style/root.css
> +  --lightblue-color-hover: #4280ea;
проблема в том, что этот цвет применяется у кнопки при наведении и у карандаша при редактировании

2023-12-09 11:01 UTC, GoveRaven commented on template/style/root.css
> +  --disabledBtn-color: #d8d8d8;
я не понял что за shadow. Ты хочешь чтобы был отдельный `root` только с переменными цветов?

2023-12-09 11:03 UTC, GoveRaven commented on template/style/task.css
> +  fill: none;
По идеи `fill` нужен, ибо будет чутка закрашен карандаш. Но `fill` есть внутри html, поэтому, да, можно убрать из css
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/6618f91d-3523-4f1a-bf52-a12ef99d164d)

2023-12-09 11:03 UTC, GoveRaven commented on template/style/task.css
> +}
Согл. Забыл убрать после идеи с аттрибутом

2023-12-09 11:05 UTC, GoveRaven commented on template/style/task.css
> +  flex-grow: 1;
Я проверил. С текстом всё в порядке и без `flex-grow`. По сути он есть, чтобы растянуть `border` при редактировании

2023-12-09 11:07 UTC, GoveRaven commented on template/style/task.css
> +  stroke: black;
Скажу больше. Это вообще лишнее свойство, ибо` .task__icon_editing` я убрал. Убрал

2023-12-09 12:15 UTC, Lexeria commented on template/style/root.css
> +  --lightblue-color-hover: #4280ea;
Тогда можно так оставить, либо подписать как-то так: `blue-hovered-color`, тип цвет на наведенный синий цвет — `lightblue`. Но можно и так оставить раз так

2023-12-09 12:16 UTC, Lexeria commented on template/style/root.css
> +  --disabledBtn-color: #d8d8d8;
Shadow DOM. Это в теме про кастомные элементы. Почитай про него и про то, как там стили задавать. И получится отдельный root для задач, да, а то как-то много тут заспамлено будто, что относится **только** к задачам

2023-12-09 14:30 UTC, GoveRaven commented on template/style/root.css
> +  --lightblue-color-hover: #4280ea;
там уже есть `lightblue` на 10 строке

2023-12-09 17:37 UTC, Lexeria commented on template/style/root.css
> +  --lightblue-color-hover: #4280ea;
Я про другое, не надо называть lightblue, это я значение обозвал так, значение с именем `blue-hovered-color`

2023-12-12 12:37 UTC, Lexeria commented on template/style/root.css
> +  --editing-color: #4280ea;
Как уменьшился файлик, кайф

2023-12-12 12:51 UTC, Lexeria requested changes

2023-12-12 12:51 UTC, Lexeria commented on login.html
> +        <div class="tasks__wrapper tasks__backlog">
А как это два блока одновременно? Мб один не блок, а модификатор/статс скорее и нужна одна земля вместо двух?

2023-12-12 12:51 UTC, Lexeria commented on login.html
> +            <template-task></template-task> <template-task></template-task>
Пока не критично, но лучше переносить на новую строчку, чтобы было заметно иерархию

2023-12-12 12:51 UTC, Lexeria commented on login.html
> +          </button>
А для отсутствия задач пока ничего не делал?

2023-12-12 12:51 UTC, Lexeria commented on style/login.css
> +@import url('root.css');
У тебя из-за этого импорта стили дважды не дублируются? В инспекторе не появляются одинаковые переменные?

2023-12-12 12:51 UTC, Lexeria commented on style/login.css
> +  border: none;
А это зачем? У кнопки, вроде, и так нет бордера изначально

2023-12-12 12:51 UTC, Lexeria commented on style/login.css
> +
Лишняя строчка

2023-12-12 12:51 UTC, Lexeria commented on style/login.css
> +  background-color: #d1e2f8;
Забавно, что у других 3-х статусах есть переменные, а тут нет

2023-12-12 12:51 UTC, Lexeria commented on style/login.css
> +}
Хмммммм

2023-12-12 12:51 UTC, Lexeria commented on style/login.css
> +  border: none;
Аналогичный вопрос про border: none — точно нужен?

2023-12-12 12:54 UTC, GoveRaven commented on login.html
> +            <template-task></template-task> <template-task></template-task>
ляяяя, я тестил как задачи вставляются и забыл их стереть

2023-12-12 12:54 UTC, GoveRaven commented on login.html
> +        <div class="tasks__wrapper tasks__backlog">
да, моя ошибка

2023-12-12 12:56 UTC, GoveRaven commented on login.html
> +          </button>
для отсутствия задач есть класс для обычных задач

2023-12-12 12:56 UTC, GoveRaven commented on style/login.css
> +@import url('root.css');
трижды появляются

2023-12-12 12:57 UTC, GoveRaven commented on style/login.css
> +@import url('root.css');
может по дефолту подключать к странице файл root.css и не делать его импорт?

2023-12-12 12:58 UTC, GoveRaven commented on style/login.css
> +  border: none;
есть бордер
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/9e11bfd3-7ba9-4943-b915-8effb23c7460)
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/c5a0fcfb-b90f-498e-9ea4-77de956bf924)

2023-12-12 12:58 UTC, GoveRaven commented on style/login.css
> +
убрал

2023-12-12 12:58 UTC, GoveRaven commented on style/login.css
> +}
ой ой ой ой ой ой

2023-12-12 12:59 UTC, GoveRaven commented on style/login.css
> +  border: none;
Нужон
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/4ef4624d-2a75-46de-b3bf-e6ab7a1f5379)
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/52e956e6-0ff9-46d5-9df3-0ad45c157552)

2023-12-12 13:04 UTC, Lexeria commented on login.html
> +          </button>
А почему класс? У нас же так карандаш будет в дом дереве, нет?

2023-12-12 13:04 UTC, Lexeria commented on style/login.css
> +@import url('root.css');
Можно и так, так логичнее и единый стиль подключения будет

2023-12-12 13:04 UTC, Lexeria commented on style/login.css
> +  border: none;
Так это outline, а не border. Или он появляется где-то когда-то?

2023-12-12 13:04 UTC, Lexeria commented on style/login.css
> +  border: none;
Хмм

2023-12-12 13:07 UTC, GoveRaven commented on login.html
> +          </button>
Мы же его убирать собрались с помощью data-атрибутов

2023-12-12 13:07 UTC, GoveRaven commented on style/login.css
> +@import url('root.css');
так он и сделал

2023-12-12 13:09 UTC, GoveRaven commented on style/login.css
> +  border: none;
А вот и не outline
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/5e5f8eef-967c-4670-9078-3c9b7eb03003)
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/f56817dd-ad87-4c75-b281-17cf38b34b53)

2023-12-12 13:12 UTC, GoveRaven commented on style/login.css
> +  background-color: #d1e2f8;
и вправду забавно. В `root.css` даже есть переменная для этого цвета, но нигде не использовалась. Исправил

2023-12-12 13:15 UTC, Lexeria commented on login.html
> +          </button>
Ага, а зачем класс? Я просто вижу примеры других задач, а отстутствие задач не вижу, ты его потом доделаешь?

2023-12-12 13:15 UTC, Lexeria commented on style/login.css
> +@import url('root.css');
Он?

2023-12-12 13:17 UTC, Lexeria commented on style/login.css
> +  border: none;
Странное, хорошо, гляну потом, главное не забыть

2023-12-12 13:19 UTC, GoveRaven commented on login.html
> +          </button>
Но у отсутствия задач такая же структура, как и у обычной задачи. Поэтому я написал стили для отсутствия задач

2023-12-12 13:20 UTC, GoveRaven commented on login.html
> +          </button>
я хотел в js с задачами написать в самом начале проверку на наличие задач в списке, если его нет, то добавлять задачу и давать ей класс, что у него нет задач и давать data-атрибут

2023-12-12 13:20 UTC, GoveRaven commented on style/login.css
> +@import url('root.css');
я сделал

2023-12-12 13:26 UTC, Lexeria commented on login.html
> +          </button>
Окейси, а логика обработки дата-аттрибута пока нет?

2023-12-12 13:30 UTC, GoveRaven commented on login.html
> +          </button>
Пока нет. Честно, мне сложно прикинуть его обработку

2023-12-12 13:48 UTC, Lexeria approved these changes

2023-12-12 14:57 UTC, merged