Функции для задач
GoveRaven/kanban-board pull request #5
Opened 2024-01-20 18:28 UTC by GoveRaven

Создание функция для создание, редактирование, удаление и перемещение задач

2024-01-26 06:56 UTC, Lexeria requested changes

2024-01-26 06:56 UTC, Lexeria commented on login.html
> +          <div class="tasks__list tasks__list_inProgress"></div>
Советую делать в едином стиле, где-то выше у тебя есть через дефис разделение слов, а тут camelCase

2024-01-26 06:56 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +const addTaskForm = document.querySelector(".new-task__form");
На всякий случай подсвечу, что `querySelector` можно применять к любому DOM-элементу. Например, так можно было бы упростить поиск `taskName`: `addTaskForm.querySelector(".new-task__name");`. По этому порядку можно еще заметить, что лучше было поменять их местами — так как сначала идет объявление формы, а потом внутри инпут

2024-01-26 06:56 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +console.log(addTaskForm);
Можно убрать, если не нужно

2024-01-26 06:56 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +addTaskForm.addEventListener("submit", (event) => createTask(event));
Можно просто `createTask`, без лишней функции-обертки

2024-01-26 06:56 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +  const text = task.querySelector(".task__text");
Советую объявлять переменные как можно ближе к месту использованию: у тебя ниже строчка идет, которой эта переменная совсем не нужна

2024-01-26 06:56 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +  window.removeEventListener("click", endEditTaskWithClick);
Я, подсвечивал, но на всякий напомню, что надо сначала объявить функцию, прежде чем ее использовать. Если не понятно, что я имею в виду, можно подробнее поговорить
P.S.> ниже увидел, что они циклически друг на друга ссылаются — это тоже не есть хорошо, но пока забьем

2024-01-26 06:56 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +  if (event.key === "Enter" || event.key === "Escape") {
Можно еще так: `["Enter", "Escape"].contains(event.key)`

2024-01-26 06:56 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +  const task = event.target.closest(".task");
А тут точно нужен `closest`? Просто `event.target` недостаточно, зная, что у него есть класс `task__icon`?

2024-01-26 06:56 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +const tasksLists = document.querySelectorAll(".tasks__list");
Ты объявил в самом начале, а используешь в самом конце — нужно стараться объявлять как можно ближе к месту использования, иначе получится каша

2024-01-26 06:56 UTC, Lexeria commented on style/task.css
> +  outline: none;
Это влияет на доступность, если убираешь, то при фокусе будет меньше интерактива. Стоит вернуть на фокус, или вместо `outline` убрать `border`, а кастомизировать `outline` — так и контент скакать не будет, если рамка появляется «в моменте»

2024-01-26 06:56 UTC, Lexeria commented on style/task.css
> +  visibility: visible;
А это тут зачем?

2024-01-26 08:31 UTC, GoveRaven commented on scripts/tasks-scripts/createTask.js
> +const addTaskForm = document.querySelector(".new-task__form");
сделал + переименовал addTaskForm в taskForm, а то странное имя я выбрал для переменной

2024-01-26 08:32 UTC, GoveRaven commented on scripts/tasks-scripts/createTask.js
> +console.log(addTaskForm);
я ещё вчера это убрал, когда заливал изменения. Хз, почему в файлах это было

2024-01-26 08:33 UTC, GoveRaven commented on scripts/tasks-scripts/createTask.js
> +addTaskForm.addEventListener("submit", (event) => createTask(event));
убрал обёртку

2024-01-26 08:34 UTC, GoveRaven commented on scripts/tasks-scripts/createTask.js
> +  const text = task.querySelector(".task__text");
сделал

2024-01-26 08:36 UTC, GoveRaven commented on scripts/tasks-scripts/editTask.js
> +  window.removeEventListener("click", endEditTaskWithClick);
я понимаю как должны быть расположены функции. Я думаю переписать чутка код, ибо он сделать через делегирование. В следующей версии попробую убрать цикличные ссылки друг на друга

2024-01-26 08:38 UTC, GoveRaven commented on scripts/tasks-scripts/editTask.js
> +  if (event.key === "Enter" || event.key === "Escape") {
мне пришлось подумать, чтобы понять как это работает, но я понял. Переписал это в коде

2024-01-26 08:39 UTC, GoveRaven commented on scripts/tasks-scripts/editTask.js
> +const tasksLists = document.querySelectorAll(".tasks__list");
в итоге эта переменная объявляется в другом файле и импортируется в этот, но учту на будущее

2024-01-26 08:41 UTC, GoveRaven commented on style/task.css
> +  outline: none;
но никаких `outline` или `border` нет у задач по макету. При фокусировки `outline` получает текст внутри

2024-01-26 08:42 UTC, GoveRaven commented on style/task.css
> +  visibility: visible;
чтобы карандаш не моргал, когда редактирование задачки идёт

2024-01-26 08:45 UTC, GoveRaven commented on scripts/tasks-scripts/editTask.js
> +  const task = event.target.closest(".task");
я думаю переделать это. В моих планах такого не будет в следующей версии

2024-01-26 17:33 UTC, Lexeria requested changes

2024-01-26 17:33 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +import { drag, drop} from "./dragAndDrop.js";
Линтер не прошелся

2024-01-26 17:33 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +  task.draggable = "true";
Каждый раз заново его навешиваем? А не проще изначально всех сделать draggable?

2024-01-26 17:33 UTC, Lexeria commented on scripts/tasks-scripts/dragAndDrop.js
> +  list.addEventListener("dragover", (event) => dragover(event));
Можно просто dragover)

2024-01-26 17:33 UTC, Lexeria commented on scripts/tasks-scripts/dragAndDrop.js
> +  task.addEventListener("dragend", () => drop(task));
Стоит расположить ниже, чем объявление функций

2024-01-26 17:33 UTC, Lexeria commented on scripts/tasks-scripts/dragAndDrop.js
> +  const selectedTask = document.querySelector(".task_dragndrop");
Не критично, но можно на строчку ниже объявить, чтобы ближе к месту использования было)

2024-01-26 17:33 UTC, Lexeria commented on scripts/tasks-scripts/dragAndDrop.js
> +function getNextElem(cursorPosition, currentElement) {
Лучше тогда полностью написать, это не общепринятые сокращения

2024-01-26 17:33 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +function endEditTask(task, text) {
Не стал придираться к task'у, и тут не буду, но подсвечу, что под именем text мы будто ожидаем обычную строчку, а не ноду

2024-01-26 17:33 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +  text.focus();
Если все еще траблы с фокусом на нужный символ, советую либо поисследовать почему стандартный пример в доке работает, либо добавить костыль, узнав про `setSelectionRange` и `createTextRange` с `move` у `range` созданного (P.S.> это еще из серии погуглить, как двигать каретку)

2024-01-26 17:33 UTC, Lexeria commented on scripts/tasks-scripts/routes.js
> +export { tasksLists, tasks };
Меня напрягает название файла)

2024-01-26 17:33 UTC, Lexeria commented on style/task.css
> +
Зачем строчку добавил?

2024-01-26 17:33 UTC, Lexeria commented on style/task.css
> +  visibility: visible;
Точно, у него когда-то `visibility: hidden` ведь?

2024-01-26 17:34 UTC, Lexeria commented on style/task.css
> +  outline: none;
А, это именно у задач, а не у текста, да?

2024-01-26 17:38 UTC, GoveRaven commented on style/task.css
> +  outline: none;
да, у задач

2024-01-26 17:39 UTC, GoveRaven commented on style/task.css
> +  visibility: visible;
по дефолту у него `visibility: hidden`, появляется если навести и если задача редактируется

2024-01-26 17:39 UTC, GoveRaven commented on scripts/tasks-scripts/createTask.js
> +import { drag, drop} from "./dragAndDrop.js";
теперь прошёлся

2024-01-26 17:42 UTC, GoveRaven commented on scripts/tasks-scripts/createTask.js
> +  task.draggable = "true";
я уже начал расписывать тебе почему так нельзя сделать, а потом понял как. Сделал в итоге

2024-01-26 17:43 UTC, GoveRaven commented on scripts/tasks-scripts/dragAndDrop.js
> +  list.addEventListener("dragover", (event) => dragover(event));
сделал

2024-01-26 17:44 UTC, GoveRaven commented on scripts/tasks-scripts/dragAndDrop.js
> +  task.addEventListener("dragend", () => drop(task));
Каждый раз говорю, что понимаю, что объявление функций нужно делать после их создания, и каждый раз пропускаю где-нибудь этот момент. Исправил

2024-01-26 17:45 UTC, GoveRaven commented on scripts/tasks-scripts/dragAndDrop.js
> +  const selectedTask = document.querySelector(".task_dragndrop");
переместил

2024-01-26 17:45 UTC, GoveRaven commented on scripts/tasks-scripts/dragAndDrop.js
> +function getNextElem(cursorPosition, currentElement) {
дописал

2024-01-26 17:46 UTC, GoveRaven commented on scripts/tasks-scripts/editTask.js
> +function endEditTask(task, text) {
понял, переименую

2024-01-26 17:48 UTC, GoveRaven commented on scripts/tasks-scripts/editTask.js
> +  text.focus();
Взял на заметку. Разберусь с этим позже.

2024-01-26 17:49 UTC, GoveRaven commented on scripts/tasks-scripts/routes.js
> +export { tasksLists, tasks };
я сделал файл с таким же названием, как и в прошлый раз, где находились какие-то общепринятые переменные и функции. Лучше переименовать?

2024-01-26 17:50 UTC, GoveRaven commented on style/task.css
> +
это случайно вышло. Видимо, я что-то туда писал, а потом удалил

2024-01-26 17:56 UTC, Lexeria commented on style/task.css
> +  outline: none;
Хорошо, но все равно не забывай про доступность — если убираешь `outline`, не забывай вернуть хотя бы на фокус — на него ориентируются при табуляции

2024-01-26 17:57 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +  text.focus();
Пока не закрываю тред, чтобы не забыть

2024-01-26 17:57 UTC, Lexeria commented on scripts/tasks-scripts/routes.js
> +export { tasksLists, tasks };
Да, потому что `routes.js` мы назвали файл, отвечающий за роутинг, поэтому и routes)

2024-01-26 17:59 UTC, Lexeria requested changes

2024-01-26 17:59 UTC, Lexeria commented on scripts/tasks-scripts/dragAndDrop.js
> +  list.addEventListener("dragover", dragover);
Ахах, `dragover` объявлен ниже)

2024-01-29 08:01 UTC, GoveRaven commented on login.html
> +          <div class="tasks__list tasks__list_inProgress"></div>
переименовал в in-progress

2024-01-30 09:14 UTC, Lexeria requested changes

2024-01-30 09:14 UTC, Lexeria commented on login.html
> +            <template-task class="task" draggable="true"></template-task>
Надо не забыть убрать потом

2024-01-30 09:14 UTC, Lexeria commented on login.html
> +          <div class="tasks__list tasks__list_trashCan">
Тут нейминг остался через camelCase

2024-01-30 19:45 UTC, GoveRaven commented on login.html
> +            <template-task class="task" draggable="true"></template-task>
ой ой ой. Я вообще случайно залил изменения этого файла. Я уберу ещё когда буду делать пустые задачки

2024-01-30 19:46 UTC, GoveRaven commented on login.html
> +          <div class="tasks__list tasks__list_trashCan">
переименовал в trash-can

2024-01-30 19:47 UTC, GoveRaven commented on scripts/tasks-scripts/routes.js
> +export { tasksLists, tasks };
переименовал файл в consts

2024-01-30 19:47 UTC, GoveRaven commented on scripts/tasks-scripts/dragAndDrop.js
> +  list.addEventListener("dragover", dragover);
my bad. Снова не уследил. Вернул на место

2024-02-01 17:26 UTC, Lexeria requested changes

2024-02-01 17:26 UTC, Lexeria commented on custom-elements/tasks.js
> +    this.draggable = "true" : ``
Можно так: `this.draggable = !this.dataset.empty`

Или так:
```js
this.draggable = `${this.dataset.empty !== "true"}`
```
или так:
```js
this.draggable = `${this.dataset.empty !== "true" || ''}`
```
если важно не передавать "false" строчкой, а именно пустую строчку

А еще у тебя почему-то в конце не обычные, а обратные кавычки

2024-02-01 17:26 UTC, Lexeria commented on custom-elements/tasks.js
> +      this.dataset.empty !== "true"
В двух местах условие, можно вытащить наверх в переменную, чтобы не дублировать эту проверку

2024-02-01 17:26 UTC, Lexeria commented on custom-elements/tasks.js
> +        : ``
Тут тоже обратные почему-то

2024-02-01 17:26 UTC, Lexeria commented on login.html
> +            data-empty-notif="Добавьте задачу выше"
notif? Что это за слово такое?

2024-02-01 17:26 UTC, Lexeria commented on login.html
> +    <script src="scripts/tasks-scripts/emptyThashCan.js" type="module"></script>
Очепятка T**h**ash

2024-02-01 17:26 UTC, Lexeria commented on scripts/tasks-scripts/createEmptyTask.js
> +function checkNoTask() {
Давай поиграемся с названием: да, тут есть проверка, но ей не ограничиваемся, выполняем какие-то действия. А какие? Как минимум удаление/добавление пустой задачи (или ничего не делания, да). Можно как-то тогда `toggleEmptyTasksIfNeeded`. Получается длинное, надо сократить... Если добивать твой вариант, то тогда хотя бы `checkNoTasks`. Но да, я сам не могу придумать что-то адекватнее)

2024-02-01 17:26 UTC, Lexeria commented on scripts/tasks-scripts/createEmptyTask.js
> +    }
А зачем тут contains, когда у нас `querySelector` к самому list'у идет как раз?

Можно было еще вот так:
```js
const task = list.querySelector(".task:not([data-empty])");
if (list.childElementCount === 0) {
    addEmptyTask(list);
} else if (task) {
    // TODO: не факт, что этот пустой таск есть, можно доработать условием выше
    removeEmptyTask(list);
}
```

2024-02-01 17:26 UTC, Lexeria commented on scripts/tasks-scripts/createEmptyTask.js
> +checkNoTask();
А зачем вызываем?

2024-02-01 17:26 UTC, Lexeria commented on scripts/tasks-scripts/createEmptyTask.js
> +    }
`addEmptyTask` и `removeEmptyTask` объявлены ниже

2024-02-01 17:26 UTC, Lexeria commented on scripts/tasks-scripts/createEmptyTask.js
> +  const noTask = document.createElement("template-task");
Лучше тогда `emptyTask`, чтобы было одно название везде

2024-02-01 17:26 UTC, Lexeria commented on scripts/tasks-scripts/createEmptyTask.js
> +  if (noTask) noTask.remove();
Можно еще так: `noTask && noTask.remove();` или так: `noTask?.remove();`

2024-02-01 17:26 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +  checkNoTask(list);
Я бы еще подумал над логикой `checkNoTask` потом, потому что тут мы точно знаем, что это в бэклог уйдет + при перетаскивании знаем, из какого в списка и в какой задачка уходит — то есть можем опираться на эти факты, а не каждый раз везде списки проверять

2024-02-01 17:26 UTC, Lexeria commented on scripts/tasks-scripts/dragAndDrop.js
> +  setTimeout(() => task.classList.add("task_dragging"), 0);
Это для проекции?

2024-02-01 17:26 UTC, Lexeria commented on scripts/tasks-scripts/dragAndDrop.js
> +  disabledBtn()
Давай переименуем в `disableButton`. Кнопку так обычно не сокращают + нам же нужно в названии функции какое-то действие, то есть `disable` вместо прилагательного/причастного `disabled`

2024-02-01 17:26 UTC, Lexeria commented on scripts/tasks-scripts/dragAndDrop.js
> +  tasksLists.forEach((list) => checkNoTask(list));
У нас `checkNoTask` не принимает аргументов, вроде, и сразу проверяем все списки везде. Мб тут просто тогда вызвать эту функцию и все?

2024-02-01 17:26 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +  checkNoTask(list);
Как вариант, добавить вызов этой функции в `addEventListener` клика кнопки создания/удаления + на событие drag'n'drop'a

2024-02-01 17:26 UTC, Lexeria commented on scripts/tasks-scripts/emptyThashCan.js
> +const trashCanBtn = document.querySelector(".trash-can__btn");
Лучше добавить воздуха, то есть отступа сверху, чтобы логически разделить импорт от последующего кода

2024-02-01 17:26 UTC, Lexeria commented on scripts/tasks-scripts/emptyThashCan.js
> +  trashCanList.innerHTML = "";
`innerHTML` опасная штука, по идее можно удалить и без нее, но так как мы тут просто затираем контент, то пусть будет так

2024-02-01 17:26 UTC, Lexeria commented on scripts/tasks-scripts/emptyThashCan.js
> +disabledBtn();
А зачем вызываем сразу?

2024-02-01 17:26 UTC, Lexeria commented on scripts/tasks-scripts/emptyThashCan.js
> +  console.log(trashCanList.contains(regularTasks))
Это лишнее

2024-02-01 17:26 UTC, Lexeria commented on scripts/tasks-scripts/emptyThashCan.js
> +  if (trashCanList.contains(regularTasks)) {
Тут аналогичная история про `contains`, который не нужен, так как `querySelector` не к `document` применяем

2024-02-01 17:52 UTC, GoveRaven commented on custom-elements/tasks.js
> +    this.draggable = "true" : ``
решения не для средних умов, но до меня дошло

2024-02-01 17:53 UTC, GoveRaven commented on custom-elements/tasks.js
> +      this.dataset.empty !== "true"
вынес

2024-02-01 17:54 UTC, GoveRaven commented on custom-elements/tasks.js
> +        : ``
а я думал, что без разницы

2024-02-01 17:54 UTC, GoveRaven commented on login.html
> +            data-empty-notif="Добавьте задачу выше"
сокращение от notification

2024-02-01 17:55 UTC, GoveRaven commented on login.html
> +    <script src="scripts/tasks-scripts/emptyThashCan.js" type="module"></script>
я весь код, почему-то писал `thash` вместо `trash`. Исправил

2024-02-01 17:56 UTC, GoveRaven commented on scripts/tasks-scripts/createEmptyTask.js
> +function checkNoTask() {
может `toggleNoTask`?

2024-02-01 18:01 UTC, GoveRaven commented on scripts/tasks-scripts/createEmptyTask.js
> +    }
да, что-то я намудрил с условиями. Исправил

2024-02-01 18:01 UTC, GoveRaven commented on scripts/tasks-scripts/createEmptyTask.js
> +checkNoTask();
чтобы появились 'пустые' задачи, если надо

2024-02-01 18:02 UTC, GoveRaven commented on scripts/tasks-scripts/createEmptyTask.js
> +  const noTask = document.createElement("template-task");
а я ведь изначально так и назвал, а потом переназвал

2024-02-02 10:26 UTC, GoveRaven commented on custom-elements/tasks.js
> +      this.dataset.empty !== "true"
вынес в переменную `empty`

2024-02-02 10:26 UTC, GoveRaven commented on custom-elements/tasks.js
> +    this.draggable = "true" : ``
переписал

2024-02-02 11:02 UTC, GoveRaven commented on scripts/tasks-scripts/createEmptyTask.js
> +  if (noTask) noTask.remove();
понял и переписал

2024-02-02 11:05 UTC, GoveRaven commented on scripts/tasks-scripts/createTask.js
> +  checkNoTask(list);
я ещё подумаю что можно сделать

2024-02-02 11:05 UTC, GoveRaven commented on scripts/tasks-scripts/dragAndDrop.js
> +  setTimeout(() => task.classList.add("task_dragging"), 0);
да. Прочитал про этот лайфках

2024-02-02 11:07 UTC, GoveRaven commented on scripts/tasks-scripts/dragAndDrop.js
> +  disabledBtn()
понял, переименовал

2024-02-02 11:10 UTC, GoveRaven commented on scripts/tasks-scripts/dragAndDrop.js
> +  tasksLists.forEach((list) => checkNoTask(list));
и вправду лишний аргумент дописал

2024-02-02 11:10 UTC, GoveRaven commented on scripts/tasks-scripts/emptyThashCan.js
> +const trashCanBtn = document.querySelector(".trash-can__btn");
добавил воздуха

2024-02-02 11:12 UTC, GoveRaven commented on scripts/tasks-scripts/emptyThashCan.js
> +  trashCanList.innerHTML = "";
я тоже думал, что опасно использовать `innerHTML`. Но там как раз ничего другого и не должно было остаться, так что я подумал, что проблем не возникнет. + хотел посмотреть что ты скажешь на него

2024-02-02 11:13 UTC, GoveRaven commented on scripts/tasks-scripts/emptyThashCan.js
> +disabledBtn();
т.к. задачки будут сохраняться, мы не знаем будет ли список пустой или нет. Поэтому по дефолту я поставил вызов функции, чтобы кнопка становилась `disabled` или не `disabled`

2024-02-02 11:14 UTC, GoveRaven commented on scripts/tasks-scripts/emptyThashCan.js
> +  console.log(trashCanList.contains(regularTasks))
Снова случайно попадают мои проверки в конечный код

2024-02-02 11:16 UTC, GoveRaven commented on scripts/tasks-scripts/emptyThashCan.js
> +  if (trashCanList.contains(regularTasks)) {
да, снова туплю с условиями. Убрал

2024-02-03 09:37 UTC, Lexeria commented on custom-elements/tasks.js
> +        : ``
Обратные используют при необходимости, когда нужно вычисления внутри использовать, если не надо, то пишут обычные

2024-02-03 09:38 UTC, Lexeria commented on login.html
> +            data-empty-notif="Добавьте задачу выше"
Не общепринятое сокращение, так лучше не сокращать. Вообще, все, что не общепринятое, лучше не сокращать, а писать полностью или придумать альтернативу

2024-02-03 11:00 UTC, Lexeria commented on scripts/tasks-scripts/emptyThashCan.js
> +disabledBtn();
Сохраняться когда? Не совсем понял

2024-02-03 11:06 UTC, Lexeria requested changes

2024-02-03 11:06 UTC, Lexeria commented on custom-elements/tasks.js
> +    const empty = this.dataset.empty
Лучше обозвать `isEmpty`, что подчеркнуть булево значение. А чтобы это и вправду было булево, то сделать так: `const isEmpty = this.dataset.empty === "true"`. Потому что, что в `this.draggable` и ниже тебе нужно только это условие

2024-02-03 11:06 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +  const sel = window.getSelection();
Лучше не сокращать, если это не общепринятые сокращения

2024-02-03 11:08 UTC, GoveRaven commented on custom-elements/tasks.js
> +        : ``
понял, принял

2024-02-03 11:09 UTC, GoveRaven commented on login.html
> +            data-empty-notif="Добавьте задачу выше"
понял, исправил

2024-02-03 11:12 UTC, GoveRaven commented on scripts/tasks-scripts/emptyThashCan.js
> +disabledBtn();
задачки будут сохраняться в облаке для пользователей. Чтобы они появлялись с самого начала, нужно вызвать функцию. Иначе будет так
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/bec00aa2-87f7-4463-b8d2-b7dd42b53525)

2024-02-03 11:13 UTC, GoveRaven commented on custom-elements/tasks.js
> +    const empty = this.dataset.empty
исправил

2024-02-03 11:14 UTC, GoveRaven commented on scripts/tasks-scripts/editTask.js
> +  const sel = window.getSelection();
дописал

2024-02-03 11:24 UTC, Lexeria commented on scripts/tasks-scripts/createEmptyTask.js
> +function checkNoTask() {
Можно так, хотя тоже сомнительно

2024-02-03 11:24 UTC, Lexeria commented on scripts/tasks-scripts/emptyThashCan.js
> +disabledBtn();
А ее нельзя сделать изначально disabled, а при добавлении в список убирать или добавлять вновь при клике на нее

2024-02-03 11:26 UTC, Lexeria requested changes

2024-02-03 11:26 UTC, Lexeria commented on custom-elements/tasks.js
> +      isEmpty !== "true"
А это условие забыли поправить. И про преттир тоже. У нас тут достаточно `!isEmpty` писать

2024-02-03 11:26 UTC, Lexeria commented on login.html
> +            data-empty-notification="Добавьте задачу выше"
Вообще, лучше `title`, у нас тут ничего нет связанного с уведомлениями в привычным его виде. Уведы — обычно про истории всплывающих окошек, push-уведомлений в телефоне и подобных

2024-02-03 11:29 UTC, GoveRaven commented on scripts/tasks-scripts/createEmptyTask.js
> +function checkNoTask() {
переделал

2024-02-03 11:30 UTC, GoveRaven commented on scripts/tasks-scripts/emptyThashCan.js
> +disabledBtn();
но если будет задача в корзине, то функция не сработает изначально и кнопка будет disabled

2024-02-03 11:34 UTC, GoveRaven commented on custom-elements/tasks.js
> +      isEmpty !== "true"
да, я щас посмотрел на это и понял, что сократить можно. Исправил

2024-02-03 11:36 UTC, GoveRaven commented on login.html
> +            data-empty-notification="Добавьте задачу выше"
исправил

2024-02-03 11:47 UTC, Lexeria commented on scripts/tasks-scripts/createEmptyTask.js
> +checkNoTask();
А когда это надо? При загрузке страницы?

2024-02-03 11:49 UTC, GoveRaven commented on scripts/tasks-scripts/createEmptyTask.js
> +checkNoTask();
этого больше нет. Я переписал скрипт
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/fdb29758-b6e3-42a5-ae88-016e78f5ed1b)

2024-02-03 11:49 UTC, Lexeria commented on scripts/tasks-scripts/emptyThashCan.js
> +disabledBtn();
Я к тому, чтобы сделать в HTML изначально `disabled`, а вызывать функцию и смотреть уже потом после смены списков из-за подгрузки с "облака", перетакскивании или клике на кнопку. Тогда вызывать ее тут в коде не понадобится, а только в нужных местах

2024-02-03 11:52 UTC, Lexeria commented on scripts/tasks-scripts/createEmptyTask.js
> +checkNoTask();
Но принцип тот же — мы вызываем функцию при загрузке страницы?

2024-02-03 11:56 UTC, GoveRaven commented on scripts/tasks-scripts/createEmptyTask.js
> +checkNoTask();
да

2024-02-03 11:57 UTC, GoveRaven commented on scripts/tasks-scripts/emptyThashCan.js
> +disabledBtn();
звучит логично. Да. Так и сделаю

2024-02-03 12:01 UTC, Lexeria commented on scripts/tasks-scripts/createEmptyTask.js
> +checkNoTask();
Хорошо, тогда это такой же кейс, как ниже про disabled кнопку — мы изначально можем везде проставить empty-task в HTML. После загрузки с "облака" в том списке, куда будем добавлять задачки, вызовем этот toggle. А в тех, что останутся без изменения — оставим как есть без вызова функции

2024-02-03 13:24 UTC, Lexeria requested changes

2024-02-03 13:24 UTC, Lexeria commented on custom-elements/tasks.js
> +        ? `    <span class="task__text" tabindex="0"></span>
А это с преттиром? А то большой отступ после кавычки какой-то

2024-02-03 13:24 UTC, Lexeria commented on login.html
>              data-empty-title="Нет задач в процессе"
Напомни, почему этот `title` у родителя, а не у самой таски?

2024-02-04 08:15 UTC, GoveRaven commented on custom-elements/tasks.js
> +        ? `    <span class="task__text" tabindex="0"></span>
кажется, что преттир игнорирует то, что находится в кавычках, но я стёр отступ

2024-02-04 08:20 UTC, GoveRaven commented on login.html
>              data-empty-title="Нет задач в процессе"
Во-первых, этих тайтлов у нас 4 штуки, которые зависят от списка. И я посчитал логичным записать тайтлы в data-атрибуты списков.
во-вторых, я не представляю что нужно написать в таску, чтобы она выбирала нужную таску и меняла их в зависимости от списка

2024-02-04 09:41 UTC, Lexeria commented on custom-elements/tasks.js
> +        ? `    <span class="task__text" tabindex="0"></span>
Та не, не должен, он такие кейсы тоже должен учитывать

2024-02-04 09:49 UTC, Lexeria commented on login.html
>              data-empty-title="Нет задач в процессе"
Можно оставить так, но по-хорошему об этом должен знать не родитель, а сам элемент. Как это можно обыграть? Например, хранить где-то так называемые "маппер" — обычный объект ключ-значение, который преобразует одно значение в другое. В нашем случае что-то типо того:
```js
{
    "backlog": "Добавьте задачу выше",
    "inProgress": "Не задач в процессе",
    ...
}
```

И внутри нашей template-таски, если у нее есть `data-empty` аттрибут, в контент подставлять `obj[currentListType]`. А откуда она будет знать, в каком она списке? Либо по классу, либо, что лучше, передавать дата аттрибут с названием списка, либо же брать его у родителя, потому что уже в этом случае родителю нормально знать, какой **он** список, а не какой текст должен быть у его ребенка. То есть что-то типа зон отвественности, которые не стоит нарушать

Если запутал сильнее и не стало лучше — давай разбираться, можно в тг)

2024-02-04 09:50 UTC, Lexeria approved these changes

2024-02-04 09:52 UTC, Lexeria commented on login.html
>              data-empty-title="Нет задач в процессе"
Кст, если передавать дата-аттрибут списка, то классы можно будет навешивать внутри template'а, что удобно, чтобы лишний раз не дублировать где-то их. А для того, чтобы понять, какой класс навесить, можно для них тоже сделать маппер по типу того, что я написал выше, но только для class name'ов

2024-02-04 09:56 UTC, GoveRaven commented on login.html
>              data-empty-title="Нет задач в процессе"
Тайтл для пустых задач относится к задачам, следовательно задачи должны знать какие у них должны быть тайтлы, а не их родители. Понял
Текст внутри пустых задач. В скрипт с шаблоном задач сделать объект с нужными текстами. Текст будет зависеть от класса родителя.
Полагаю, всё понял

2024-02-04 09:59 UTC, Lexeria commented on login.html
>              data-empty-title="Нет задач в процессе"
Не от класса родителя, а от собственного класса, а что еще лучше, просто от дата-аттрибуте типа списка, который можем навесить на родителя

2024-02-04 10:20 UTC, Lexeria requested changes

2024-02-04 10:20 UTC, Lexeria commented on custom-elements/tasks.js
> +    }
А давай вытащим это, как поле класса. В чем прикол? В том, что на каждую созданную задачу мы будем заново создавать этот список, который у нас не будет меняться. Если вытащить поле класса, то оно у всех будет одно плюс-минус (если статическим не забудем сделать). Либо же можно еще вытащить за класс, просто выше, либо в другой файл — такие варианты тоже имеют быть, чтобы много раз не создавать один и тот же объект

2024-02-04 10:20 UTC, Lexeria commented on login.html
> +            data-list-type="inProgress"
Кст, заметь какую махинацию сча сделали — у нас есть список inProgress и есть стили, которые навешиваем для него. Это не обязательно, но в какие-то моменты для удобства мы можем просто навешивать стили не по классу, а по дата-аттрибуту. Но это так, чтобы ты просто помнил про это и держал в голове такую возможность, сейчас оставим, как есть)

2024-02-04 10:20 UTC, Lexeria commented on scripts/tasks-scripts/createEmptyTask.js
> +  text.textContent = titles[this.parentNode.dataset.listType];
Я туплю, но где мы тут берем `titles`?

2024-02-04 10:23 UTC, GoveRaven commented on scripts/tasks-scripts/createEmptyTask.js
> +  text.textContent = titles[this.parentNode.dataset.listType];
оно в шаблоне задач

2024-02-04 11:11 UTC, Lexeria approved these changes

2024-02-04 11:14 UTC, merged