Облачное хранилище
GoveRaven/kanban-board pull request #7
Opened 2024-02-08 10:48 UTC by GoveRaven

2024-02-16 16:39 UTC, Lexeria requested changes

2024-02-16 16:39 UTC, Lexeria commented on index.html
> +    <script></script>
Это что за пустой скрипт?)

2024-02-16 16:39 UTC, Lexeria commented on login.html
> +    <script
А нам выше все скрипты надо подключать? Какие-то же просто через импорты получают нужные функции. Или оно ломается?

2024-02-16 16:39 UTC, Lexeria commented on scripts/authStateChange.js
> +import { auth } from "./firebaseConfig.js";
Лучше порядок иметь одинаковый: сначала сторонние скрипты, потом ниже твои

2024-02-16 16:39 UTC, Lexeria commented on scripts/authorization.js
> +import { redirectToLoginPage } from "./routes.js";
А это где-то используется тут?

2024-02-16 16:39 UTC, Lexeria commented on scripts/logOut.js
> +import { redirectToMainPage } from "./routes.js";
Это где-то используется?

2024-02-16 16:39 UTC, Lexeria commented on scripts/realtimeDatabase.js
> +import { createTask } from "./tasks-scripts/createTask.js";
Тоже про порядок импортов скриптов: лучше сначала заимпортить все стороннее, а потом свое, чтобы был логический порядок

2024-02-16 16:39 UTC, Lexeria commented on scripts/realtimeDatabase.js
> +  for (let i = 0; i < Object.values(tasks).length; i++) {
У тебя уже есть переменная, которая равна `Object.values(tasks)`, можно не дублировать

2024-02-16 16:39 UTC, Lexeria commented on scripts/realtimeDatabase.js
> +    createTask(values[i].title, values[i].taskType, keys[i]);
Если нужны ключи и значения одновременно, можно использовать `Object.entries(tasks)` и проитерироваться так:

```javascript
for (const [key, value] of Object.entries(tasks)) {
    createTask(value.title, value.taskType, key);
}
```

Мог немного синтаксис перепутать, но в целом так как-то

2024-02-16 16:39 UTC, Lexeria commented on scripts/realtimeDatabase.js
> +    uid: uid,
Можно убрать `: uid` — js сам подставляет ключ по строковому названию переменной, если нет двоеточия

2024-02-16 16:39 UTC, Lexeria commented on scripts/realtimeDatabase.js
> +  if (task.dataset.key !== undefined) return;
Можно так: `!!task.dataset.key`

2024-02-16 16:39 UTC, Lexeria commented on scripts/realtimeDatabase.js
> +    title: title,
Тут и ниже можно убрать двоеточие и после него переменную, как уже писал выше про uid

2024-02-16 16:39 UTC, Lexeria commented on scripts/realtimeDatabase.js
> +  updates[`users/${userUid}/tasks/${newPostKey}`] = DBTask;
Вообще, у тебя в нескольких местах дублируются нейминги полей/стора в бд, я бы их лучше вытащил в переменные, чтобы если вдруг переименовать решим, нигде не забыли это сделать

2024-02-16 16:39 UTC, Lexeria commented on scripts/realtimeDatabase.js
> +function removeTaskFromDB(key) {
Лучше один нейминг использовать, где-то key, где-то uid, если не ошибаюсь

2024-02-16 16:39 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +      key && (task.dataset.key = key);
Можно просто: `this.dataset.key = key`

2024-02-16 16:39 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +      addUserTasksInDB(task, taskTitle, taskType);
Переименуй функцию в единственное число, если таска одна передается всегда

2024-02-16 16:39 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +function creatTaskOnSite(event) {
Букву пропустил в первом слове

2024-02-16 16:39 UTC, Lexeria commented on scripts/tasks-scripts/dragAndDrop.js
> +    text.textContent,
Порядок я бы поменял: сначала обычно говорят, где поменять, а потом что поменять

2024-02-17 07:14 UTC, GoveRaven commented on index.html
> +    <script></script>
это я лаудер отдельно подключал и не убрал

2024-02-17 07:15 UTC, GoveRaven commented on login.html
> +    <script
я позже проверю все скрипты, что импортирует куда и скажу точно

2024-02-17 07:16 UTC, GoveRaven commented on scripts/authStateChange.js
> +import { auth } from "./firebaseConfig.js";
сделал

2024-02-17 07:17 UTC, GoveRaven commented on scripts/logOut.js
> +import { redirectToMainPage } from "./routes.js";
redirectToMainPage? Используется. При выходе из профиля тебя бросает на первую страницу

2024-02-17 07:17 UTC, GoveRaven commented on scripts/realtimeDatabase.js
> +import { createTask } from "./tasks-scripts/createTask.js";
сделал

2024-02-17 07:18 UTC, GoveRaven commented on scripts/realtimeDatabase.js
> +  for (let i = 0; i < Object.values(tasks).length; i++) {
это я какое-то мясо написал, пока делал эту функцию. Убрал

2024-02-17 07:20 UTC, GoveRaven commented on scripts/realtimeDatabase.js
> +    createTask(values[i].title, values[i].taskType, keys[i]);
я думал, чтобы использовать `Object.entries()`, но путался в коде цикла. Перепишу, спасибо. Даже не подумал чтобы задать 2 переменные как `[key, value]`

2024-02-17 07:21 UTC, GoveRaven commented on scripts/realtimeDatabase.js
> +    uid: uid,
Точно. Убрал

2024-02-17 07:22 UTC, GoveRaven commented on scripts/realtimeDatabase.js
> +  if (task.dataset.key !== undefined) return;
два восклицательных знаков сначала смутило, но понял зачем. Исправил

2024-02-17 07:23 UTC, GoveRaven commented on scripts/realtimeDatabase.js
> +    title: title,
да, прочитав про uid, сразу понял, что тут также будет. Исправил

2024-02-17 07:27 UTC, GoveRaven commented on scripts/realtimeDatabase.js
> +  updates[`users/${userUid}/tasks/${newPostKey}`] = DBTask;
эта строка имеет значение ключа, которое постоянно меняется, поэтому я не вынес его в переменную. Как выглядит итоговый вариант:

`const path = `users/${userUid}/tasks/`;`

Тогда в коде будет:

` updates[`${path}/${newPostKey}`] = DBTask;`

Пойдёт?

2024-02-17 07:28 UTC, GoveRaven commented on scripts/realtimeDatabase.js
> +function removeTaskFromDB(key) {
На 51 строке вместо `key` используется `newPostKey`. Исправил

2024-02-17 07:49 UTC, GoveRaven commented on scripts/tasks-scripts/createTask.js
> +      key && (task.dataset.key = key);
нет, нельзя. Я специально написал как в коде.
Функция `createTask `возникает в 2 случаях:

1. Создание задачи из БД
2. Создание задачи с сайта 

У задач есть поле data-key, которое является их ключом, который помогает их найти в БД. Когда страница загружается, то сначала происходит создание задач из ДБ. В БД у задач уже есть их ключи, всё загружается хорошо, отлично.
Проблема возникает при создании на странице. У функции `createTask ` 3 аргумента: заголовок, тип и ключ. При создании из БД все аргументы есть, т.к. всё есть. Но при создании с сайта аргумент ключа отсутствует, то бишь undefined. Если написать `this.dataset.key = key`, то его ключом станет не фактический ключ.

Забудь всё что я писал выше. Я переписал эту строку, но чтобы всё работало пришлось переписать условие в функции `addUserTasksInDB`, которые ты поправлял выше. Там надо было убрать один восклицательный знак. Снова до меня доходит что-то, когда я начинаю тебе объяснять это.
Исправил

2024-02-17 07:49 UTC, GoveRaven commented on scripts/tasks-scripts/createTask.js
> +      addUserTasksInDB(task, taskTitle, taskType);
переименовал

2024-02-17 07:50 UTC, GoveRaven commented on scripts/tasks-scripts/createTask.js
> +function creatTaskOnSite(event) {
и вправду. Исправил

2024-02-17 07:50 UTC, GoveRaven commented on scripts/tasks-scripts/dragAndDrop.js
> +    text.textContent,
понял. Поменял

2024-02-17 07:56 UTC, GoveRaven commented on scripts/authorization.js
> +import { redirectToLoginPage } from "./routes.js";
Это при авторизации используется. Когда пользователь авторизируется, то его перенаправляет на вторую страницу

2024-02-17 12:36 UTC, GoveRaven commented on scripts/tasks-scripts/createTask.js
> +      key && (task.dataset.key = key);
Нет. Без этого никак.
Как я и говорил выше, функция `createTask` возникает в 2 случаях. Когда задачка создаётся через БД, то ключ есть, он задаётся всё нормально. Если ключа нет, то условие  `key && (task.dataset.key = key)` дальше не идёт и у таски нет ключа, что и логично, она же только создана, а ключ создаётся при занесении в БД.
Позже функция `creatTask` вызывает функцию `addUserTaskInDB`, добавляющая задачу в БД. Она должна добавить её в том случае, если создана на сайте. Задачи созданные на сайте и добавленные из БД отличаются только наличием ключа. Поэтому, что функция `addUserTaskInDB` не дублировала уже имеющиеся таски в БД, нужно это условие

2024-02-17 18:05 UTC, Lexeria commented on login.html
> +    <script
Окс, просто нам где-то достаточно подключить только основные скрипты, чтобы такой портянки не было. Можно, например, сделать основной скрипт для страницы, который будет импортить все другие скрипты у себя, а тут только его импортировать. Но это не обязательно, просто, чтобы много не получалось

2024-02-17 18:06 UTC, Lexeria commented on scripts/authorization.js
> +import { redirectToLoginPage } from "./routes.js";
Я просто в коде ниже не вижу использования

2024-02-17 18:06 UTC, Lexeria commented on scripts/logOut.js
> +import { redirectToMainPage } from "./routes.js";
Я про использование в этом файле где-нибудь ниже

2024-02-17 18:07 UTC, Lexeria commented on scripts/realtimeDatabase.js
> +    createTask(values[i].title, values[i].taskType, keys[i]);
Это деструктуризация Object.entries)

2024-02-17 18:08 UTC, Lexeria commented on scripts/realtimeDatabase.js
> +  updates[`users/${userUid}/tasks/${newPostKey}`] = DBTask;
Да, это имел в виду, только userUid пропустил. Тип ты обращаешься к ключам по типу users, tasks, которые ты не меняешь по идее и в строчке хардкодишь

2024-02-17 18:13 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +      key && (task.dataset.key = key);
Нет, это я все понимаю, но если ты пишешь, как я предложил, и key — `undefined`, когда ты ничего не передал, то ничего не поменяется ведь. Так как изначально `this.dataset.key` и так `undefined`. Не пойму окончательно проблему, что плохого в том, чтобы так писать 

UPD: понял теперь, когда есть ключ, чтобы его не перезаписать на `undefined`

2024-02-17 18:18 UTC, Lexeria requested changes

2024-02-17 18:18 UTC, Lexeria commented on scripts/realtimeDatabase.js
> +  const key = push(child(dbRef, "tasks")).key;
Можно с деструктуризацией: `const { key } = push(dbRef, “tasks”))`

2024-02-17 18:18 UTC, Lexeria commented on scripts/realtimeDatabase.js
> +  const key = push(child(dbRef, "tasks")).key;
Возможно, не до конца понял, что я имел в виду — у тебя есть ключи для именований хранилищ в бд, которые не меняются — `users`, `tasks` и мб что-то еще, что используется в коде. Лучше вытащить их в константы и переиспользовать в строчках не захардкоженные варианты, а переменные

2024-02-17 18:18 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +      task.dataset.key = key;
Если не работает, то надо вернуть

2024-02-17 18:21 UTC, GoveRaven commented on scripts/authorization.js
> +import { redirectToLoginPage } from "./routes.js";
на 13 строке используется

2024-02-17 18:21 UTC, GoveRaven commented on scripts/logOut.js
> +import { redirectToMainPage } from "./routes.js";
да, на 8 строке

2024-02-17 18:24 UTC, GoveRaven commented on scripts/tasks-scripts/createTask.js
> +      task.dataset.key = key;
да, я ещё не сделал коммит на это

2024-02-18 11:44 UTC, GoveRaven commented on scripts/realtimeDatabase.js
> +  const key = push(child(dbRef, "tasks")).key;
я не понял как ты хочешь делать деструктуризацию и зачем

2024-02-18 11:54 UTC, Lexeria commented on scripts/realtimeDatabase.js
> +  const key = push(child(dbRef, "tasks")).key;
Я пример привел, фигурные скобки добавил, чтобы не писать `.key` в конце

А по поводу второго коммента вот:

```javascript
// TODO: можно переименовать, не помню, как это сущность называется в БД, ключ или не ключ...
const usersKey = "users";
const tasksKey = "tasks";
...
const { key } = push(child(dbRef, tasksKey));
...
path = `${usersKey}/${userUid}/${tasksKey}/`;
...
${usersKey}/${userUid}/${tasksKey}/${newPostKey}
```

2024-02-18 12:28 UTC, GoveRaven commented on scripts/realtimeDatabase.js
> +  const key = push(child(dbRef, "tasks")).key;
Теперь понял. Сделал

2024-02-18 12:34 UTC, GoveRaven commented on scripts/realtimeDatabase.js
> +  const key = push(child(dbRef, "tasks")).key;
На счёт деструктуризации. Там есть косяк, что задача добавляется в БД юзера, но и просто добавляется в БД не в папку юзера
![image](https://github.com/GoveRaven/kanban-board/assets/123263785/92eee9c2-dae4-4af1-b62a-db6f2e235ad9)

2024-02-18 13:35 UTC, Lexeria commented on scripts/realtimeDatabase.js
> +  const key = push(child(dbRef, "tasks")).key;
Это не по поводу де структуризации, наверное. Деструктуризация — фигурные скобочка, или квадратные, когда мы деструктурируем (то есть меняем структуру) объекта/массива:

```javascript
const { key } = { key: “123”, }; // key === “123”
const [a, b] = [1, 2, 3]; // a === 1, b === 2
```

2024-02-18 19:48 UTC, GoveRaven commented on login.html
> +    <script
Я удалил все ненужные скрипты, но ты сказал, что что-то расскажешь по поводу этого

2024-02-19 13:15 UTC, Lexeria approved these changes

2024-02-21 13:12 UTC, merged