Последние патчи
GoveRaven/kanban-board pull request #9
Opened 2024-02-24 09:35 UTC by GoveRaven

2024-02-25 14:25 UTC, Lexeria requested changes

2024-02-25 14:25 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +  if (!value) return
Неплохо, но так мы лишаемся всплывающей ошибки на `required` значение. Как вариант, можно еще было сделать обработчик `onChange`, в котором каждый раз применяли бы `trim`, подменяя значение инпута

2024-02-25 14:25 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +function endEditTask(task, taskText, originalText) {  if (taskText.innerText.length === 0) {
Форматтер не прошелся, строчка выглядит страшно из-за этого)

2024-02-25 14:25 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +    taskText.innerText = originalText;
Я бы оставлял хотя бы один символ, а не изначальный текст. В личке объяснял, что это не самый приятный текст, когда ты стараешься стереть и просто лишнего стираешь, а тебе возвращают оригинальный текст. Хотя тут тоже не понятно, что лучше будет. Самое лучшее — подсмотреть, как сделано в ноушене

2024-02-26 09:12 UTC, Lexeria requested changes

2024-02-26 09:12 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
>    if (["Enter", "Escape"].includes(event.key)) {
Блин, а условие дублируется в двух местах получается?

2024-02-26 09:12 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
>    if (!event.target.closest(".task")) {
И тот тоже

2024-02-26 09:12 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +function eventsToogle(task, taskText) {
Это не toggle, мы по-честному скорее просто навешиваем листенеры. Да, тут упомянаются ремувы, но мы их не дергаем, просто объявляем в отличии от addEventListener

2024-02-26 09:12 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +function eventsToogle(task, taskText) {
+ обычно стараются все же глагол в начало названия функции тащить

2024-02-26 09:12 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +    const condition =
`condition` — не говорящее название, лучше обозвать как-то попонятнее по типу `needRemoveListeners`, что-то типа название переменной в виде вопроса, на которые ответ `true` или `false`. Еще вариант нейминги с приставкой `is/are/has/have` в начале

2024-02-26 12:05 UTC, GoveRaven commented on scripts/tasks-scripts/editTask.js
> +    taskText.innerText = originalText;
это исправил. Теперь если стереть весь текст, то задачка будет пустой

2024-02-26 12:05 UTC, GoveRaven commented on scripts/tasks-scripts/editTask.js
> +function endEditTask(task, taskText, originalText) {  if (taskText.innerText.length === 0) {
уже прошёлся

2024-02-26 12:05 UTC, GoveRaven commented on scripts/tasks-scripts/editTask.js
>    if (["Enter", "Escape"].includes(event.key)) {
да

2024-02-26 12:07 UTC, GoveRaven commented on scripts/tasks-scripts/editTask.js
> +    const condition =
я думал об этом, но посчитал, что `condition` будет подходящим

2024-02-26 12:08 UTC, GoveRaven commented on scripts/tasks-scripts/editTask.js
> +function eventsToogle(task, taskText) {
переименовал в addEvents

2024-02-26 12:11 UTC, GoveRaven commented on scripts/tasks-scripts/createTask.js
> +  if (!value) return
это как-то сомнительно будет выглядеть. Пользователь захочет добавить пробелы, а они просто не будут добавляться. А если в середине инпута будут вставлять пробелы, то они вставятся. Я могу сделать то, что ты предложил, но считаю это сомнительным

2024-02-26 12:34 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +  if (!value) return
Спасибо за замечание по пробелам, надо подумать, как делать тогда. Но раз ноушен разрешает создавать пустые задачи и при редактировании оставлять пустыми, то можем забить)

2024-02-26 12:39 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
>    if (["Enter", "Escape"].includes(event.key)) {
Эт не оч, давай мб подумаем, как это исправить. Потому что поменяем в одном месте — в другом забудем. Я пока вижу два варианта:
1. Прокидывать функцию для удаления обработчика, которую вызовем внутри if'а
2. Внутри if'а здесь делать `return true;`, и записывать это возвращаемое значение, как одну из переменной для `condition` твоего, из которых потом составим условие

2024-02-26 12:40 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +    const condition =
Это как название функция `function` :)

2024-02-26 12:50 UTC, Lexeria requested changes

2024-02-26 12:50 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +function addEvents(task, taskText) {
Я бы докрутил название: мы не просто добавляем какие-то ивенты, мы добавляем слушатели ивентов. А лучше еще пояснить какие — `addEditTaskEventsListeners`, например

2024-02-26 12:55 UTC, GoveRaven commented on scripts/tasks-scripts/createTask.js
> +  if (!value) return
то бишь, можно убрать это ограничение?

2024-02-26 12:58 UTC, GoveRaven commented on scripts/tasks-scripts/editTask.js
> +function addEvents(task, taskText) {
переименовал

2024-02-26 14:47 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +  if (!value) return
Да

2024-02-26 14:48 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +      event.preventDefault();
```javascript
// TODO: понять, почему клик не сбрасывает в отличии от клавиш
```

2024-02-26 17:03 UTC, GoveRaven commented on scripts/tasks-scripts/createTask.js
> +  if (!value) return
сделал

2024-02-28 12:54 UTC, Lexeria requested changes

2024-02-28 12:54 UTC, Lexeria commented on scripts/addUserInfo.js
> +  window.addEventListener("click", someFunc);
Функции лучше объявлять выше места использования, чем их использование

2024-02-28 12:54 UTC, Lexeria commented on scripts/addUserInfo.js
> +function someFunc() {
Красивое название, но давай сделаем его еще лучше и понятнее

2024-02-28 12:54 UTC, Lexeria commented on scripts/addUserInfo.js
> +  if (logOut.classList.contains("user__logOut-close")) {
`toggle` возвращает булево значение, обозначающее есть ли сейчас данный класс в итоге или не. Давай воспользуемся этой полезной штукой)

2024-02-28 12:54 UTC, Lexeria commented on scripts/addUserInfo.js
> +  if (logOut.classList.contains("user__logOut-close")) {
А можно даже без присваивания, добавив `&&`, но тогда строчка длинной получится, наверное. В общем, на твой вкус

2024-02-28 12:54 UTC, Lexeria commented on scripts/logOut.js
> +
Лайк, места не хватало подышать)

2024-02-28 14:03 UTC, GoveRaven commented on scripts/addUserInfo.js
> +function someFunc() {
ой ой ой ой. Я для первого применения решил так обозвать и забыл переименовать

2024-02-28 14:04 UTC, GoveRaven commented on scripts/logOut.js
> +
я даже не заметил, что там есть место

2024-02-28 14:05 UTC, GoveRaven commented on scripts/addUserInfo.js
> +  window.addEventListener("click", someFunc);
переместил выше

2024-02-28 14:08 UTC, GoveRaven commented on scripts/addUserInfo.js
> +  if (logOut.classList.contains("user__logOut-close")) {
не не не. Погоди. `toogle` добавляет класс, если его нет, и убирает если его нет. А `contains` проверяет наличие класса и возвращает булевое значение

2024-02-28 14:56 UTC, Lexeria commented on scripts/addUserInfo.js
> +  if (logOut.classList.contains("user__logOut-close")) {
Не, `toggle` помимо своей функции тогла имеет возвращаемое значение, которое заменит твой `contains` и будет выглядеть лаконичнее. Можешь в доке почитать)

2024-02-28 14:59 UTC, Lexeria commented on scripts/addUserInfo.js
> +  if (logOut.classList.contains("user__logOut-close")) {
А вообще, нам точно `toggle` нужен? А то выглядит так будто мы точно знаем, что конкретно сейчас нам надо добавить или убрать класс (но мб ошибаюсь)

2024-02-28 15:00 UTC, GoveRaven commented on scripts/addUserInfo.js
> +  if (logOut.classList.contains("user__logOut-close")) {
так-то да, нам нужен только `remove`

2024-02-28 15:04 UTC, GoveRaven commented on scripts/addUserInfo.js
> +  if (logOut.classList.contains("user__logOut-close")) {
нет. Погоди (снова). Нам нужен именно `toggle`, ибо по сути на 19 строчке выпадашка появляется и исчезает. Больше нигде это не прописывается

2024-03-01 10:55 UTC, Lexeria commented on scripts/addUserInfo.js
> +  if (logOut.classList.contains("user__logOut-close")) {
А почему функция тогда называется **hide**? Это немного путает

2024-03-01 10:57 UTC, Lexeria requested changes

2024-03-01 10:57 UTC, Lexeria commented on style/task.css
> +  cursor: default;
В тг писал про курсор, можно добить, чтобы он был более отзывчивым

2024-03-01 12:23 UTC, GoveRaven commented on scripts/addUserInfo.js
> +  if (logOut.classList.contains("user__logOut-close")) {
я думал, что имя подходящее. Выпадашка есть, но мы её прячем. заменю hide на remove

2024-03-01 12:24 UTC, GoveRaven commented on style/task.css
> +  cursor: default;
да, да. Я уже залил когда ты написал про курсор. Поменяю в следующем коммите

2024-03-01 16:26 UTC, Lexeria commented on scripts/addUserInfo.js
> +  if (logOut.classList.contains("user__logOut-close")) {
Не, почему называется **hide**, а в функции используем `toggle` для класса `close`? Звучит так, как будто мы точно знаем, что будем скрывать и `toggle` не нужен

2024-03-01 17:32 UTC, GoveRaven commented on scripts/addUserInfo.js
> +  if (logOut.classList.contains("user__logOut-close")) {
`toggle` нужен, ибо только эта функция влияет на классы

2024-03-01 19:40 UTC, Lexeria commented on scripts/addUserInfo.js
> +  if (logOut.classList.contains("user__logOut-close")) {
Тогда я чет не пойму, почему все же hide в названии функци: мы же не только hide делаем, но и unhide раз тогглим классы, нет?

2024-03-02 07:31 UTC, GoveRaven commented on scripts/addUserInfo.js
> +  if (logOut.classList.contains("user__logOut-close")) {
получается так. Значит да, название не подходит

2024-03-02 09:24 UTC, Lexeria commented on custom-elements/tasks.js
> +    !isEmpty ? (this.tabIndex = 0) : "";
А где это используется? Вижу внизу в двух местах есть tabindex, которое и так зависит от условия `isEmpty`

2024-03-02 09:24 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
>  function createTask(taskTitle, taskType, key) {
Функция получилось громоздкой, я об этом в тг сказал, править не надо, но обычно, когда она такая большая стоит декомпозировать все же

2024-03-02 09:24 UTC, Lexeria commented on scripts/tasks-scripts/createTask.js
> +      event.preventDefault();
Я же правильно понимаю, что на другие клавиши нам не нужен `preventDefault`?

2024-03-02 09:24 UTC, Lexeria commented on style/root.css
> +  --focus-visible-color: #a1a1a1;
Лайк за новую переменную, хотя уже есть переменная с таким цветом выше

2024-03-02 09:26 UTC, GoveRaven commented on style/root.css
> +  --focus-visible-color: #a1a1a1;
ой ой ой

2024-03-02 09:27 UTC, GoveRaven commented on custom-elements/tasks.js
> +    !isEmpty ? (this.tabIndex = 0) : "";
без него можно навестись табуляцией на пустые задачки

2024-03-02 09:27 UTC, GoveRaven commented on scripts/tasks-scripts/createTask.js
> +      event.preventDefault();
да

2024-03-02 09:54 UTC, Lexeria commented on style/root.css
> +  --focus-visible-color: #a1a1a1;
Оставить, как есть. Просто подметил, что хорошо, что не использовал существующую: да, там такой же цвет, но логика использования и название другое, не подходящее — поэтому нормально, что продублировали

2024-03-02 12:18 UTC, Lexeria commented on scripts/tasks-scripts/editTask.js
> +    taskText.innerText = originText;
Оригинальный же с trim’ом?

2024-03-02 12:19 UTC, GoveRaven commented on scripts/tasks-scripts/editTask.js
> +    taskText.innerText = originText;
оригинальный - текст, который был. Он по умолчанию не может быть без `trim()`. `trim()` происходит когда создают задачку, либо когда редактируют с подтверждением. Так что нельзя с помощью отмены сделать задачку с лишними пробелами в начале или конце

2024-03-02 13:42 UTC, Lexeria approved these changes

2024-03-02 17:37 UTC, Lexeria commented on scripts/tasks-scripts/dragAndDrop.js
> +});
Напомни еще раз, почему windows? У нас больше нигде событий с dragover’ом нет, куда бы мы могли перетащить этот prevent?

2024-03-02 18:42 UTC, GoveRaven commented on scripts/tasks-scripts/dragAndDrop.js
> +});
можно `document` вместо `window`. Если делать `event.preventDefault()` для списков, то курсор будет нормальным только над списками. Чтобы он был нормальным на всей странице, я дал событие `window`

2024-03-03 06:13 UTC, GoveRaven commented on scripts/tasks-scripts/dragAndDrop.js
> +});
я повесил событие на window, чтобы курсор был адекватным на всей странице. Изначально я писал event.preventDefault() для списков на событие dragover, но тогда курсор был адекватным только над списками. Можно вместо window написать document.

2024-03-03 08:27 UTC, Lexeria commented on scripts/tasks-scripts/dragAndDrop.js
> +});
А до этих правок курсор везде «запрет», даже над списками?

2024-03-03 11:45 UTC, GoveRaven commented on scripts/tasks-scripts/dragAndDrop.js
> +});
да

2024-03-03 12:11 UTC, Lexeria commented on scripts/tasks-scripts/dragAndDrop.js
> +});
А может сделать все же не на `window` или `document`, а на списки? Логично, что он показывает «Запрет» там, куда мы не можем опустить

2024-03-03 12:18 UTC, GoveRaven commented on scripts/tasks-scripts/dragAndDrop.js
> +});
хорошо

2024-03-03 15:45 UTC, Lexeria approved these changes

2024-03-04 13:50 UTC, merged